name: PHP Lint & Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_sqlite
          coverage: none

      - name: Validate PHP syntax (Lint)
        run: |
          find . -type f -name "*.php" -not -path "./vendor/*" -exec php -l {} \;

      - name: Build Docker image
        run: docker build -t bilet-satin-alma .

      - name: Validate Docker Compose config
        run: docker compose config

      - name: Run container and test web response
        run: |
          docker compose up -d
          sleep 5
          curl -I http://localhost:8080 | grep "200 OK"
          docker compose down